version: '3.8'

services:
  mongo:
    image: mongo:8.0
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017

  client:
    build:
      context: ../client
    volumes:
      - ../client:/usr/src/app
    ports:
      - 5001:5001

  server:
    depends_on:
      - mongo
    build:
      context: ../server
    volumes:
      - ../server:/usr/src/app
    ports:
      - 5000:5000


volumes:
  mongo-data:
